title: liuli's blog

description: Welcome to my blog, Now I'm a rookie to use the github and edit code.Please kindly advise.
# 主题
theme: jekyll-theme-time-machine

markdown: kramdown

footer-links:
  zhihu: https://www.zhihu.com/people/liu-li-xin-meng-mei-ru-xue
  email: 2424130136@qq.com
  github: liuli-heaven
  twitter: https://x.com/ruliDream
